# Generated by Django 5.1.7 on 2025-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('printed_fabric', 'Printed Fabric'), ('solid_dyed_fabric', 'Solid Dyed Fabric'), ('fabric_set', 'Fabric Set'), ('dyed_fabric', 'Dyed Fabric'), ('shop_look', 'Shop Look'), ('womens_wear', "Women's Wear")], max_length=100, null=True),
        ),
    ]
