# Generated by Django 5.1.6 on 2025-03-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/banners/'),
        ),
    ]
